import { createApiClient } from './client';
import { createAiApi } from './ai';
import { createAuthApi } from './auth';
import { createAgentListingsApi } from './agentListings';
import { createAgentProfilesApi } from './agentProfiles';
import { createBuilderProjectsApi } from './builderProjects';
import { createFavoritesApi } from './favorites';
import { createInvoicesApi } from './invoices';
import { createPaymentsApi } from './payments';
import { createPropertiesApi } from './properties';
import { createSupportApi } from './support';
import { createUsersApi } from './users';
import { expoTokenStorage } from '../storage/tokenStorage';

export const api = createApiClient(expoTokenStorage);
export const authApi = createAuthApi(api);
export const propertiesApi = createPropertiesApi(api);
export const paymentsApi = createPaymentsApi(api);
export const supportApi = createSupportApi(api);
export const usersApi = createUsersApi(api);
export const builderProjectsApi = createBuilderProjectsApi(api);
export const agentProfilesApi = createAgentProfilesApi(api);
export const agentListingsApi = createAgentListingsApi(api);
export const invoicesApi = createInvoicesApi(api);
export const aiApi = createAiApi(api);
export const favoritesApi = createFavoritesApi(api);
